REWARD_VALUE = 10
MOVING_COST = 2

EPSILON = 0.1
GAMMA = 0.9

MAX_CARS = 20
MAX_CAR_SWITCH = 5

LAMBDA_RETURN_LOC_1 = 3
LAMBDA_REQUEST_LOC_1 = 3
LAMBDA_RETURN_LOC_2 = 2
LAMBDA_REQUEST_LOC_2 = 4

ONE_FREE_CAR_MOVEMENT_FROM_1_TO_2 = True
LIMITED_PARKING_SPACE = True
MAX_CAR_SINGLE_PARKING_SPACE = 10
COST_ADDITIONAL_PARKING_SPACE = 4
